# Generated by Django 4.2.7 on 2023-11-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contacts_category_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
    ]
